import re

REQUIRED_SPACE_MULTIPLIER = 1.1
HASH_SUFFIX = ".md5"
TAR_HASH_SUFFIX = ".tar.md5"
COMPRESSED_ARCHIVE_SUFFIX = ".tar.lz"
ENCRYPTED_ARCHIVE_SUFFIX = ".tar.lz.gpg"
COMPRESSED_ARCHIVE_HASH_SUFFIX = ".tar.lz.md5"
ENCRYPTED_ARCHIVE_HASH_SUFFIX = ".tar.lz.gpg.md5"
LISTING_SUFFIX = ".tar.lst"
READ_CHUNK_BYTE_SIZE = 1000 * 1000 * 100
ENCRYPTION_ALGORITHM = "AES256"
ENV_VAR_MAPPER_MAX_CPUS = "ARCHIVER_MAX_CPUS_ENV_VAR"
DEFAULT_COMPRESSION_LEVEL = 6

MD5_LINE_REGEX = re.compile(r'(\S+)\s+(\S.*)')
