# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version: [ 3.8, 3.9 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install system dependencies
      run: sudo apt-get install plzip tar gnupg2 build-essential
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # jdupes is an optional dependency in the precondition checks, need it here for testing
    - name: Install jdupes
      run: |
        git clone https://codeberg.org/jbruchon/libjodycode.git
        cd libjodycode
        git checkout v3.0
        make && sudo make install
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib" >> $GITHUB_ENV
        cd ..
        git clone https://codeberg.org/jbruchon/jdupes.git
        cd jdupes
        git checkout v1.27
        make && sudo make install
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
